AppVersion: 1.0.0

Server:
  Development: true

Kafka:
  Brokers: ["host.docker.internal:9091", "host.docker.internal:9092", "host.docker.internal:9093"]

Logger:
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

PostgresDB:
  HOST: "postgresql"
  PORT: "5432"
  User: "pguser"
  Password: "pgpwd4balances"
  DB: "balances"
  SSL: "disable"
